### ISSUE TITLE
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools

### ISSUE THREAD

**Issue by CChisuwo** [ROpdam/docker-dash-example#6]
I found your medium article on containerizing dash apps  for deployment on the web and interating the apps to a CICD pipeline and it was a very eye opening read.

However, upon cloning the repository i failed to spin up the docker container as I was getting the error message below:
`
 '' ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/usr/local/lib/python3.8/site-packages/werkzeug/debug/[tbtools.py](https://tbtools.py/))
`
Any help will be appreciated

**Comment by ropdam** [comment]
Thanks @CChisuwo, fixed the issue in https://github.com/ROpdam/docker-dash-example/pull/5. Issue came from https://github.com/plotly/dash/issues/1992. Locked the werkzeug version now at 2.0.3.

Should work now!
